"""Build the self-hosted Noto Sans TC slices and Figtree WOFF2 for the frontend.

MASTER.md section 5 requires both faces to be served from our own domain
(offline availability, no visitor IP sent to a font CDN). Shipping the whole
Noto Sans TC variable font (~12 MB TTF) to a 75+ user's tablet is not
acceptable, so the font is cut into unicode-range slices the same way Google
Fonts serves it: the browser then downloads only the slices a page needs.

Inputs (OFL 1.1, downloaded once; not committed):
  --noto     NotoSansTC[wght].ttf  from google/fonts ofl/notosanstc
  --figtree  Figtree[wght].ttf     from google/fonts ofl/figtree
Slice boundaries: noto-sans-tc-unicode-ranges.json next to this script.

Outputs (committed):
  packages/frontend/public/fonts/noto-sans-tc/v1/noto-sans-tc-<n>.woff2
  packages/frontend/src/app/fonts/noto-sans-tc.css   (one @font-face per slice)
  packages/frontend/src/app/fonts/figtree-variable.woff2

Requires: python -m pip install fonttools brotli  (build-time tool only).
Run from the repository root:
  python scripts/fonts/build_noto_sans_tc_slices.py --noto <ttf> --figtree <ttf>
"""

from __future__ import annotations

import argparse
import io
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[2]
FRONTEND = ROOT / "packages" / "frontend"
SLICE_DIR = FRONTEND / "public" / "fonts" / "noto-sans-tc" / "v1"
CSS_OUT = FRONTEND / "src" / "app" / "fonts" / "noto-sans-tc.css"
FIGTREE_OUT = FRONTEND / "src" / "app" / "fonts" / "figtree-variable.woff2"
RANGES = Path(__file__).with_name("noto-sans-tc-unicode-ranges.json")
WEIGHT_RANGE = (400, 700)  # MASTER.md 5: 400 / 500 / 700 are the weights in use


def parse_unicode_range(spec: str) -> list[int]:
    codepoints: list[int] = []
    for token in spec.split(","):
        token = token.strip().upper().removeprefix("U+")
        if "-" in token:
            lo, hi = token.split("-")
            codepoints.extend(range(int(lo, 16), int(hi, 16) + 1))
        else:
            codepoints.append(int(token, 16))
    return codepoints


def restrict_weight_axis(font: TTFont) -> bytes:
    """Partial instancing: keep the font variable but only between 400 and 700."""
    limited = instancer.instantiateVariableFont(font, {"wght": WEIGHT_RANGE}, inplace=False)
    buffer = io.BytesIO()
    limited.save(buffer)
    return buffer.getvalue()


def subset_slice(source: bytes, codepoints: list[int]) -> TTFont | None:
    font = TTFont(io.BytesIO(source))
    cmap = font.getBestCmap()
    present = [cp for cp in codepoints if cp in cmap]
    if not present:
        return None
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.drop_tables += ["DSIG"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=present)
    subsetter.subset(font)
    font.flavor = "woff2"
    return font


def build_noto(noto_path: Path) -> list[tuple[int, str, int]]:
    ranges = json.loads(RANGES.read_text(encoding="utf-8"))["slices"]
    print(f"restricting wght axis of {noto_path.name} to {WEIGHT_RANGE} ...")
    limited = restrict_weight_axis(TTFont(noto_path))
    SLICE_DIR.mkdir(parents=True, exist_ok=True)
    for stale in SLICE_DIR.glob("*.woff2"):
        stale.unlink()
    written: list[tuple[int, str, int]] = []
    for entry in ranges:
        index = entry["slice"]
        font = subset_slice(limited, parse_unicode_range(entry["unicode_range"]))
        if font is None:
            print(f"slice {index}: no glyphs in this font, skipped")
            continue
        target = SLICE_DIR / f"noto-sans-tc-{index}.woff2"
        font.save(target)
        size = target.stat().st_size
        written.append((index, entry["unicode_range"], size))
        print(f"slice {index}: {size / 1024:.1f} KB")
    return written


def write_css(written: list[tuple[int, str, int]]) -> None:
    lines = [
        "/* Generated by scripts/fonts/build_noto_sans_tc_slices.py — do not edit by hand.",
        "   Noto Sans TC (OFL 1.1), self-hosted per MASTER.md section 5, cut into the",
        "   same unicode-range slices Google Fonts uses so only needed slices load. */",
        "",
    ]
    for index, unicode_range, _ in written:
        lines += [
            "@font-face {",
            "  font-family: 'Noto Sans TC';",
            "  font-style: normal;",
            f"  font-weight: {WEIGHT_RANGE[0]} {WEIGHT_RANGE[1]};",
            "  font-display: swap;",
            f"  src: url('/fonts/noto-sans-tc/v1/noto-sans-tc-{index}.woff2') format('woff2');",
            f"  unicode-range: {unicode_range};",
            "}",
            "",
        ]
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {CSS_OUT.relative_to(ROOT)} with {len(written)} faces")


def build_figtree(figtree_path: Path) -> None:
    font = TTFont(figtree_path)
    font.flavor = "woff2"
    FIGTREE_OUT.parent.mkdir(parents=True, exist_ok=True)
    font.save(FIGTREE_OUT)
    print(f"wrote {FIGTREE_OUT.relative_to(ROOT)} ({FIGTREE_OUT.stat().st_size / 1024:.1f} KB)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--noto", type=Path, required=True, help="NotoSansTC[wght].ttf")
    parser.add_argument("--figtree", type=Path, required=True, help="Figtree[wght].ttf")
    args = parser.parse_args()
    build_figtree(args.figtree)
    written = build_noto(args.noto)
    write_css(written)
    total = sum(size for _, _, size in written)
    print(f"{len(written)} slices, {total / 1024 / 1024:.2f} MB total")


if __name__ == "__main__":
    main()
